# frozen_string_literal: true

# rubocop:disable all
# Seeds for a Country model in a standard Relational Database.
# Schema is:
# Country { name: 'String', iso_alpha_two: 'String', iso_alpha_three: 'String', iso_numeric: 'Integer' }
#
[
  { name: 'Afghanistan', official_name: 'The Islamic Republic of Afghanistan', iso_alpha_two: 'AF', iso_alpha_three: 'AFG', iso_numeric: '004', tld: '.af' },
  { name: 'Åland Islands', official_name: 'Åland', iso_alpha_two: 'AX', iso_alpha_three: 'ALA', iso_numeric: '248', tld: '' },
  { name: 'Albania', official_name: 'The Republic of Albania', iso_alpha_two: 'AL', iso_alpha_three: 'ALB', iso_numeric: '008', tld: '' },
  { name: 'Algeria', official_name: '', iso_alpha_two: 'DZ', iso_alpha_three: 'DZA', iso_numeric: '012', tld: '' },
  { name: 'American Samoa', official_name: '', iso_alpha_two: 'AS', iso_alpha_three: 'ASM', iso_numeric: '016', tld: '' },
  { name: 'Andorra', official_name: '', iso_alpha_two: 'AD', iso_alpha_three: 'ND', iso_numeric: '020', tld: '' },
  { name: 'Angola', official_name: '', iso_alpha_two: 'AO', iso_alpha_three: 'AGO', iso_numeric: '024', tld: '' },
  { name: 'Anguilla', official_name: '', iso_alpha_two: 'AI', iso_alpha_three: 'AIA', iso_numeric: '660', tld: '' },
  { name: 'Antarctica', official_name: '', iso_alpha_two: 'AQ', iso_alpha_three: 'ATA', iso_numeric: '010', tld: '' },
  { name: 'Antigua And Barbuda', official_name: '', iso_alpha_two: 'AG', iso_alpha_three: 'ATG', iso_numeric: '028', tld: '' },
  { name: 'Argentina', official_name: '', iso_alpha_two: 'AR', iso_alpha_three: 'ARG', iso_numeric: '032', tld: '' },
  { name: 'Armenia', official_name: '', iso_alpha_two: 'AM', iso_alpha_three: 'ARM', iso_numeric: '051', tld: '' },
  { name: 'Aruba', official_name: '', iso_alpha_two: 'AW', iso_alpha_three: 'ABW', iso_numeric: '533', tld: '' },
  { name: 'Australia', official_name: '', iso_alpha_two: 'AU', iso_alpha_three: 'AUS', iso_numeric: '036', tld: '' },
  { name: 'Austria', official_name: '', iso_alpha_two: 'AT', iso_alpha_three: 'AUT', iso_numeric: '040', tld: '' },
  { name: 'Azerbaijan', official_name: '', iso_alpha_two: 'AZ', iso_alpha_three: 'AZE', iso_numeric: '031', tld: '' },
  { name: 'Bahamas', official_name: '', iso_alpha_two: 'BS', iso_alpha_three: 'BHS', iso_numeric: '044', tld: '' },
  { name: 'Bahrain', official_name: '', iso_alpha_two: 'BH', iso_alpha_three: 'BHR', iso_numeric: '048', tld: '' },
  { name: 'Bangladesh', official_name: '', iso_alpha_two: 'BD', iso_alpha_three: 'BGD', iso_numeric: '050', tld: '' },
  { name: 'Barbados', official_name: '', iso_alpha_two: 'BB', iso_alpha_three: 'BRB', iso_numeric: '052', tld: '' },
  { name: 'Belarus', official_name: '', iso_alpha_two: 'BY', iso_alpha_three: 'BLR', iso_numeric: '112', tld: '' },
  { name: 'Belgium', official_name: '', iso_alpha_two: 'BE', iso_alpha_three: 'BEL', iso_numeric: '056', tld: '' },
  { name: 'Belize', official_name: '', iso_alpha_two: 'BZ', iso_alpha_three: 'BLZ', iso_numeric: '084', tld: '' },
  { name: 'Benin', official_name: '', iso_alpha_two: 'BJ', iso_alpha_three: 'BEN', iso_numeric: '204', tld: '' },
  { name: 'Bermuda', official_name: '', iso_alpha_two: 'BM', iso_alpha_three: 'BMU', iso_numeric: '060', tld: '' },
  { name: 'Bhutan', official_name: '', iso_alpha_two: 'BT', iso_alpha_three: 'BTN', iso_numeric: '064', tld: '' },
  { name: 'Bolivia', official_name: '', iso_alpha_two: 'BO', iso_alpha_three: 'BOL', iso_numeric: '068', tld: '' },
  { name: 'Bosnia and Herzegovina', official_name: '', iso_alpha_two: 'BA', iso_alpha_three: 'BIH', iso_numeric: '070', tld: '' },
  { name: 'Botswana', official_name: '', iso_alpha_two: 'BW', iso_alpha_three: 'BWA', iso_numeric: '072', tld: '' },
  { name: 'Bouvet Island', official_name: '', iso_alpha_two: 'BV', iso_alpha_three: 'BVT', iso_numeric: '074', tld: '' },
  { name: 'Brazil', official_name: '', iso_alpha_two: 'BR', iso_alpha_three: 'BRA', iso_numeric: '076', tld: '' },
  { name: 'British Indian Ocean Territory', official_name: '', iso_alpha_two: 'IO', iso_alpha_three: 'IOT', iso_numeric: '086', tld: '' },
  { name: 'British Virgin Islands', official_name: '', iso_alpha_two: 'VG', iso_alpha_three: 'VGB', iso_numeric: '092', tld: '' },
  { name: 'Brunei Darussalam', official_name: '', iso_alpha_two: 'BN', iso_alpha_three: 'BRN', iso_numeric: '096', tld: '' },
  { name: 'Bulgaria', official_name: '', iso_alpha_two: 'BG', iso_alpha_three: 'BGR', iso_numeric: '100', tld: '' },
  { name: 'Burkina Faso', official_name: '', iso_alpha_two: 'BF', iso_alpha_three: 'BFA', iso_numeric: '854', tld: '' },
  { name: 'Burundi', official_name: '', iso_alpha_two: 'BI', iso_alpha_three: 'BDI', iso_numeric: '108', tld: '' },
  { name: 'Cambodia', official_name: '', iso_alpha_two: 'KH', iso_alpha_three: 'KHM', iso_numeric: '116', tld: '' },
  { name: 'Cameroon', official_name: '', iso_alpha_two: 'CM', iso_alpha_three: 'CMR', iso_numeric: '120', tld: '' },
  { name: 'Canada', official_name: '', iso_alpha_two: 'CA', iso_alpha_three: 'CAN', iso_numeric: '124', tld: '' },
  { name: 'Cape Verde', official_name: '', iso_alpha_two: 'CV', iso_alpha_three: 'CPV', iso_numeric: '132', tld: '' },
  { name: 'Cayman Islands', official_name: '', iso_alpha_two: 'KY', iso_alpha_three: 'CYM', iso_numeric: '136', tld: '' },
  { name: 'Central African Republic', official_name: '', iso_alpha_two: 'CF', iso_alpha_three: 'CAF', iso_numeric: '140', tld: '' },
  { name: 'Chad', official_name: '', iso_alpha_two: 'TD', iso_alpha_three: 'TCD', iso_numeric: '148', tld: '' },
  { name: 'Chile', official_name: '', iso_alpha_two: 'CL', iso_alpha_three: 'CHL', iso_numeric: '152', tld: '' },
  { name: 'China', official_name: '', iso_alpha_two: 'CN', iso_alpha_three: 'CHN', iso_numeric: '156', tld: '' },
  { name: 'Christmas Island', official_name: '', iso_alpha_two: 'CX', iso_alpha_three: 'CXR', iso_numeric: '162', tld: '' },
  { name: 'Cocos (Keeling) Islands', official_name: '', iso_alpha_two: 'CC', iso_alpha_three: 'CCK', iso_numeric: '166', tld: '' },
  { name: 'Colombia', official_name: '', iso_alpha_two: 'CO', iso_alpha_three: 'COL', iso_numeric: '170', tld: '' },
  { name: 'Comoros', official_name: '', iso_alpha_two: 'KM', iso_alpha_three: 'COM', iso_numeric: '174', tld: '' },
  { name: 'Congo (Brazzaville)', official_name: '', iso_alpha_two: 'CG', iso_alpha_three: 'COG', iso_numeric: '178', tld: '' },
  { name: 'Congo (Kinshasa)', official_name: '', iso_alpha_two: 'CD', iso_alpha_three: 'COD', iso_numeric: '180', tld: '' },
  { name: 'Cook Islands', official_name: '', iso_alpha_two: 'CK', iso_alpha_three: 'COK', iso_numeric: '184', tld: '' },
  { name: 'Costa Rica', official_name: '', iso_alpha_two: 'CR', iso_alpha_three: 'CRI', iso_numeric: '188', tld: '' },
  { name: 'Croatia', official_name: '', iso_alpha_two: 'HR', iso_alpha_three: 'HRV', iso_numeric: '191', tld: '' },
  { name: 'Cuba', official_name: '', iso_alpha_two: 'CU', iso_alpha_three: 'CUB', iso_numeric: '192', tld: '' },
  { name: 'Cyprus', official_name: '', iso_alpha_two: 'CY', iso_alpha_three: 'CYP', iso_numeric: '196', tld: '' },
  { name: 'Czech Republic', official_name: '', iso_alpha_two: 'CZ', iso_alpha_three: 'CZE', iso_numeric: '203', tld: '' },
  { name: 'Côte d\'Ivoire', official_name: '', iso_alpha_two: 'CI', iso_alpha_three: 'CIV', iso_numeric: '384', tld: '' },
  { name: 'Denmark', official_name: '', iso_alpha_two: 'DK', iso_alpha_three: 'DNK', iso_numeric: '208', tld: '' },
  { name: 'Djibouti', official_name: '', iso_alpha_two: 'DJ', iso_alpha_three: 'DJI', iso_numeric: '262', tld: '' },
  { name: 'Dominica', official_name: '', iso_alpha_two: 'DM', iso_alpha_three: 'DMA', iso_numeric: '212', tld: '' },
  { name: 'Dominican Republic', official_name: '', iso_alpha_two: 'DO', iso_alpha_three: 'DOM', iso_numeric: '214', tld: '' },
  { name: 'Ecuador', official_name: '', iso_alpha_two: 'EC', iso_alpha_three: 'ECU', iso_numeric: '218', tld: '' },
  { name: 'Egypt', official_name: '', iso_alpha_two: 'EG', iso_alpha_three: 'EGY', iso_numeric: '818', tld: '' },
  { name: 'El Salvador', official_name: '', iso_alpha_two: 'SV', iso_alpha_three: 'SLV', iso_numeric: '222', tld: '' },
  { name: 'Equatorial Guinea', official_name: '', iso_alpha_two: 'GQ', iso_alpha_three: 'GNQ', iso_numeric: '226', tld: '' },
  { name: 'Eritrea', official_name: '', iso_alpha_two: 'ER', iso_alpha_three: 'ERI', iso_numeric: '232', tld: '' },
  { name: 'Estonia', official_name: '', iso_alpha_two: 'EE', iso_alpha_three: 'EST', iso_numeric: '233', tld: '' },
  { name: 'Ethiopia', official_name: '', iso_alpha_two: 'ET', iso_alpha_three: 'ETH', iso_numeric: '231', tld: '' },
  { name: 'Falkland Islands (Malvinas)', official_name: '', iso_alpha_two: 'FK', iso_alpha_three: 'FLK', iso_numeric: '238', tld: '' },
  { name: 'Faroe Islands', official_name: '', iso_alpha_two: 'FO', iso_alpha_three: 'FRO', iso_numeric: '234', tld: '' },
  { name: 'Fiji', official_name: '', iso_alpha_two: 'FJ', iso_alpha_three: 'FJI', iso_numeric: '242', tld: '' },
  { name: 'Finland', official_name: '', iso_alpha_two: 'FI', iso_alpha_three: 'FIN', iso_numeric: '246', tld: '' },
  { name: 'France', official_name: '', iso_alpha_two: 'FR', iso_alpha_three: 'FRA', iso_numeric: '250', tld: '' },
  { name: 'French Guiana', official_name: '', iso_alpha_two: 'GF', iso_alpha_three: 'GUF', iso_numeric: '254', tld: '' },
  { name: 'French Polynesia', official_name: '', iso_alpha_two: 'PF', iso_alpha_three: 'PYF', iso_numeric: '258', tld: '' },
  { name: 'French Southern Territories', official_name: '', iso_alpha_two: 'TF', iso_alpha_three: 'ATF', iso_numeric: '260', tld: '' },
  { name: 'Gabon', official_name: '', iso_alpha_two: 'GA', iso_alpha_three: 'GAB', iso_numeric: '266', tld: '' },
  { name: 'Gambia', official_name: '', iso_alpha_two: 'GM', iso_alpha_three: 'GMB', iso_numeric: '270', tld: '' },
  { name: 'Georgia', official_name: '', iso_alpha_two: 'GE', iso_alpha_three: 'GEO', iso_numeric: '268', tld: '' },
  { name: 'Germany', official_name: '', iso_alpha_two: 'DE', iso_alpha_three: 'DEU', iso_numeric: '276', tld: '' },
  { name: 'Ghana', official_name: '', iso_alpha_two: 'GH', iso_alpha_three: 'GHA', iso_numeric: '288', tld: '' },
  { name: 'Gibraltar', official_name: '', iso_alpha_two: 'GI', iso_alpha_three: 'GIB', iso_numeric: '292', tld: '' },
  { name: 'Greece', official_name: '', iso_alpha_two: 'GR', iso_alpha_three: 'GRC', iso_numeric: '300', tld: '' },
  { name: 'Greenland', official_name: '', iso_alpha_two: 'GL', iso_alpha_three: 'GRL', iso_numeric: '304', tld: '' },
  { name: 'Grenada', official_name: '', iso_alpha_two: 'GD', iso_alpha_three: 'GRD', iso_numeric: '308', tld: '' },
  { name: 'Guadeloupe', official_name: '', iso_alpha_two: 'GP', iso_alpha_three: 'GLP', iso_numeric: '312', tld: '' },
  { name: 'Guam', official_name: '', iso_alpha_two: 'GU', iso_alpha_three: 'GUM', iso_numeric: '316', tld: '' },
  { name: 'Guatemala', official_name: '', iso_alpha_two: 'GT', iso_alpha_three: 'GTM', iso_numeric: '320', tld: '' },
  { name: 'Guernsey', official_name: '', iso_alpha_two: 'GG', iso_alpha_three: 'GGY', iso_numeric: '831', tld: '' },
  { name: 'Guinea', official_name: '', iso_alpha_two: 'GN', iso_alpha_three: 'GIN', iso_numeric: '324', tld: '' },
  { name: 'Guinea-Bissau', official_name: '', iso_alpha_two: 'GW', iso_alpha_three: 'GNB', iso_numeric: '624', tld: '' },
  { name: 'Guyana', official_name: '', iso_alpha_two: 'GY', iso_alpha_three: 'GUY', iso_numeric: '328', tld: '' },
  { name: 'Haiti', official_name: '', iso_alpha_two: 'HT', iso_alpha_three: 'HTI', iso_numeric: '332', tld: '' },
  { name: 'Heard and McDonald Islands', official_name: '', iso_alpha_two: 'HM', iso_alpha_three: 'HMD', iso_numeric: '334', tld: '' },
  { name: 'Holy See (Vatican City State)', official_name: '', iso_alpha_two: 'VA', iso_alpha_three: 'VAT', iso_numeric: '336', tld: '' },
  { name: 'Honduras', official_name: '', iso_alpha_two: 'HN', iso_alpha_three: 'HND', iso_numeric: '340', tld: '' },
  { name: 'Hong Kong, SAR China', official_name: '', iso_alpha_two: 'HK', iso_alpha_three: 'HKG', iso_numeric: '344', tld: '' },
  { name: 'Hungary', official_name: '', iso_alpha_two: 'HU', iso_alpha_three: 'HUN', iso_numeric: '348', tld: '' },
  { name: 'Iceland', official_name: '', iso_alpha_two: 'IS', iso_alpha_three: 'ISL', iso_numeric: '352', tld: '' },
  { name: 'India', official_name: '', iso_alpha_two: 'IN', iso_alpha_three: 'IND', iso_numeric: '356', tld: '' },
  { name: 'Indonesia', official_name: '', iso_alpha_two: 'ID', iso_alpha_three: 'IDN', iso_numeric: '360', tld: '' },
  { name: 'Iran, Islamic Republic of', official_name: '', iso_alpha_two: 'IR', iso_alpha_three: 'IRN', iso_numeric: '364', tld: '' },
  { name: 'Iraq', official_name: '', iso_alpha_two: 'IQ', iso_alpha_three: 'IRQ', iso_numeric: '368', tld: '' },
  { name: 'Ireland', official_name: '', iso_alpha_two: 'IE', iso_alpha_three: 'IRL', iso_numeric: '372', tld: '' },
  { name: 'Isle of Man', official_name: '', iso_alpha_two: 'IM', iso_alpha_three: 'IMN', iso_numeric: '833', tld: '' },
  { name: 'Israel', official_name: '', iso_alpha_two: 'IL', iso_alpha_three: 'ISR', iso_numeric: '376', tld: '' },
  { name: 'Italy', official_name: '', iso_alpha_two: 'IT', iso_alpha_three: 'ITA', iso_numeric: '380', tld: '' },
  { name: 'Jamaica', official_name: '', iso_alpha_two: 'JM', iso_alpha_three: 'JAM', iso_numeric: '388', tld: '' },
  { name: 'Japan', official_name: '', iso_alpha_two: 'JP', iso_alpha_three: 'JPN', iso_numeric: '392', tld: '' },
  { name: 'Jersey', official_name: '', iso_alpha_two: 'JE', iso_alpha_three: 'JEY', iso_numeric: '832', tld: '' },
  { name: 'Jordan', official_name: '', iso_alpha_two: 'JO', iso_alpha_three: 'JOR', iso_numeric: '400', tld: '' },
  { name: 'Kazakhstan', official_name: '', iso_alpha_two: 'KZ', iso_alpha_three: 'KAZ', iso_numeric: '398', tld: '' },
  { name: 'Kenya', official_name: '', iso_alpha_two: 'KE', iso_alpha_three: 'KEN', iso_numeric: '404', tld: '' },
  { name: 'Kiribati', official_name: '', iso_alpha_two: 'KI', iso_alpha_three: 'KIR', iso_numeric: '296', tld: '' },
  { name: 'Korea (North)', official_name: '', iso_alpha_two: 'KP', iso_alpha_three: 'PRK', iso_numeric: '408', tld: '' },
  { name: 'Korea (South)', official_name: '', iso_alpha_two: 'KR', iso_alpha_three: 'KOR', iso_numeric: '410', tld: '' },
  { name: 'Kuwait', official_name: '', iso_alpha_two: 'KW', iso_alpha_three: 'KWT', iso_numeric: '414', tld: '' },
  { name: 'Kyrgyzstan', official_name: '', iso_alpha_two: 'KG', iso_alpha_three: 'KGZ', iso_numeric: '417', tld: '' },
  { name: 'Laos', official_name: '', iso_alpha_two: 'LA', iso_alpha_three: 'LAO', iso_numeric: '418', tld: '' },
  { name: 'Latvia', official_name: '', iso_alpha_two: 'LV', iso_alpha_three: 'LVA', iso_numeric: '428', tld: '' },
  { name: 'Lebanon', official_name: '', iso_alpha_two: 'LB', iso_alpha_three: 'LBN', iso_numeric: '422', tld: '' },
  { name: 'Lesotho', official_name: '', iso_alpha_two: 'LS', iso_alpha_three: 'LSO', iso_numeric: '426', tld: '' },
  { name: 'Liberia', official_name: '', iso_alpha_two: 'LR', iso_alpha_three: 'LBR', iso_numeric: '430', tld: '' },
  { name: 'Libya', official_name: '', iso_alpha_two: 'LY', iso_alpha_three: 'LBY', iso_numeric: '434', tld: '' },
  { name: 'Liechtenstein', official_name: '', iso_alpha_two: 'LI', iso_alpha_three: 'LIE', iso_numeric: '438', tld: '' },
  { name: 'Lithuania', official_name: '', iso_alpha_two: 'LT', iso_alpha_three: 'LTU', iso_numeric: '440', tld: '' },
  { name: 'Luxembourg', official_name: '', iso_alpha_two: 'LU', iso_alpha_three: 'LUX', iso_numeric: '442', tld: '' },
  { name: 'Macao', official_name: '', iso_alpha_two: 'MO', iso_alpha_three: 'MAC', iso_numeric: '446', tld: '' },
  { name: 'Macedonia', official_name: '', iso_alpha_two: 'MK', iso_alpha_three: 'MKD', iso_numeric: '807', tld: '' },
  { name: 'Madagascar', official_name: '', iso_alpha_two: 'MG', iso_alpha_three: 'MDG', iso_numeric: '450', tld: '' },
  { name: 'Malawi', official_name: '', iso_alpha_two: 'MW', iso_alpha_three: 'MWI', iso_numeric: '454', tld: '' },
  { name: 'Malaysia', official_name: '', iso_alpha_two: 'MY', iso_alpha_three: 'MYS', iso_numeric: '458', tld: '' },
  { name: 'Maldives', official_name: '', iso_alpha_two: 'MV', iso_alpha_three: 'MDV', iso_numeric: '462', tld: '' },
  { name: 'Mali', official_name: '', iso_alpha_two: 'ML', iso_alpha_three: 'MLI', iso_numeric: '466', tld: '' },
  { name: 'Malta', official_name: '', iso_alpha_two: 'MT', iso_alpha_three: 'MLT', iso_numeric: '470', tld: '' },
  { name: 'Marshall Islands', official_name: '', iso_alpha_two: 'MH', iso_alpha_three: 'MHL', iso_numeric: '584', tld: '' },
  { name: 'Martinique', official_name: '', iso_alpha_two: 'MQ', iso_alpha_three: 'MTQ', iso_numeric: '474', tld: '' },
  { name: 'Mauritania', official_name: '', iso_alpha_two: 'MR', iso_alpha_three: 'MRT', iso_numeric: '478', tld: '' },
  { name: 'Mauritius', official_name: '', iso_alpha_two: 'MU', iso_alpha_three: 'MUS', iso_numeric: '480', tld: '' },
  { name: 'Mayotte', official_name: '', iso_alpha_two: 'YT', iso_alpha_three: 'MYT', iso_numeric: '175', tld: '' },
  { name: 'Mexico', official_name: '', iso_alpha_two: 'MX', iso_alpha_three: 'MEX', iso_numeric: '484', tld: '' },
  { name: 'Micronesia', official_name: '', iso_alpha_two: 'FM', iso_alpha_three: 'FSM', iso_numeric: '583', tld: '' },
  { name: 'Moldova', official_name: '', iso_alpha_two: 'MD', iso_alpha_three: 'MDA', iso_numeric: '498', tld: '' },
  { name: 'Monaco', official_name: '', iso_alpha_two: 'MC', iso_alpha_three: 'MCO', iso_numeric: '492', tld: '' },
  { name: 'Mongolia', official_name: '', iso_alpha_two: 'MN', iso_alpha_three: 'MNG', iso_numeric: '496', tld: '' },
  { name: 'Montenegro', official_name: '', iso_alpha_two: 'ME', iso_alpha_three: 'MNE', iso_numeric: '499', tld: '' },
  { name: 'Montserrat', official_name: '', iso_alpha_two: 'MS', iso_alpha_three: 'MSR', iso_numeric: '500', tld: '' },
  { name: 'Morocco', official_name: '', iso_alpha_two: 'MA', iso_alpha_three: 'MAR', iso_numeric: '504', tld: '' },
  { name: 'Mozambique', official_name: '', iso_alpha_two: 'MZ', iso_alpha_three: 'MOZ', iso_numeric: '508', tld: '' },
  { name: 'Myanmar', official_name: '', iso_alpha_two: 'MM', iso_alpha_three: 'MMR', iso_numeric: '104', tld: '' },
  { name: 'Namibia', official_name: '', iso_alpha_two: 'NA', iso_alpha_three: 'NAM', iso_numeric: '516', tld: '' },
  { name: 'Nauru', official_name: '', iso_alpha_two: 'NR', iso_alpha_three: 'NRU', iso_numeric: '520', tld: '' },
  { name: 'Nepal', official_name: '', iso_alpha_two: 'NP', iso_alpha_three: 'NPL', iso_numeric: '524', tld: '' },
  { name: 'Netherlands', official_name: '', iso_alpha_two: 'NL', iso_alpha_three: 'NLD', iso_numeric: '528', tld: '' },
  { name: 'Netherlands Antilles', official_name: '', iso_alpha_two: 'AN', iso_alpha_three: 'ANT', iso_numeric: '530', tld: '' },
  { name: 'New Caledonia', official_name: '', iso_alpha_two: 'NC', iso_alpha_three: 'NCL', iso_numeric: '540', tld: '' },
  { name: 'New Zealand', official_name: '', iso_alpha_two: 'NZ', iso_alpha_three: 'NZL', iso_numeric: '554', tld: '' },
  { name: 'Nicaragua', official_name: '', iso_alpha_two: 'NI', iso_alpha_three: 'NIC', iso_numeric: '558', tld: '' },
  { name: 'Niger', official_name: '', iso_alpha_two: 'NE', iso_alpha_three: 'NER', iso_numeric: '562', tld: '' },
  { name: 'Nigeria', official_name: '', iso_alpha_two: 'NG', iso_alpha_three: 'NGA', iso_numeric: '566', tld: '' },
  { name: 'Niue', official_name: '', iso_alpha_two: 'NU', iso_alpha_three: 'NIU', iso_numeric: '570', tld: '' },
  { name: 'Norfolk Island', official_name: '', iso_alpha_two: 'NF', iso_alpha_three: 'NFK', iso_numeric: '574', tld: '' },
  { name: 'Northern Mariana Islands', official_name: '', iso_alpha_two: 'MP', iso_alpha_three: 'MNP', iso_numeric: '580', tld: '' },
  { name: 'Norway', official_name: '', iso_alpha_two: 'NO', iso_alpha_three: 'NOR', iso_numeric: '578', tld: '' },
  { name: 'Oman', official_name: '', iso_alpha_two: 'OM', iso_alpha_three: 'OMN', iso_numeric: '512', tld: '' },
  { name: 'Pakistan', official_name: '', iso_alpha_two: 'PK', iso_alpha_three: 'PAK', iso_numeric: '586', tld: '' },
  { name: 'Palau', official_name: '', iso_alpha_two: 'PW', iso_alpha_three: 'PLW', iso_numeric: '585', tld: '' },
  { name: 'Palestinian Territory', official_name: '', iso_alpha_two: 'PS', iso_alpha_three: 'PSE', iso_numeric: '275', tld: '' },
  { name: 'Panama', official_name: '', iso_alpha_two: 'PA', iso_alpha_three: 'PAN', iso_numeric: '591', tld: '' },
  { name: 'Papua New Guinea', official_name: '', iso_alpha_two: 'PG', iso_alpha_three: 'PNG', iso_numeric: '598', tld: '' },
  { name: 'Paraguay', official_name: '', iso_alpha_two: 'PY', iso_alpha_three: 'PRY', iso_numeric: '600', tld: '' },
  { name: 'Peru', official_name: '', iso_alpha_two: 'PE', iso_alpha_three: 'PER', iso_numeric: '604', tld: '' },
  { name: 'Philippines', official_name: '', iso_alpha_two: 'PH', iso_alpha_three: 'PHL', iso_numeric: '608', tld: '' },
  { name: 'Pitcairn', official_name: '', iso_alpha_two: 'PN', iso_alpha_three: 'PCN', iso_numeric: '612', tld: '' },
  { name: 'Poland', official_name: '', iso_alpha_two: 'PL', iso_alpha_three: 'POL', iso_numeric: '616', tld: '' },
  { name: 'Portugal', official_name: '', iso_alpha_two: 'PT', iso_alpha_three: 'PRT', iso_numeric: '620', tld: '' },
  { name: 'Puerto Rico', official_name: '', iso_alpha_two: 'PR', iso_alpha_three: 'PRI', iso_numeric: '630', tld: '' },
  { name: 'Qatar', official_name: '', iso_alpha_two: 'QA', iso_alpha_three: 'QAT', iso_numeric: '634', tld: '' },
  { name: 'Reunion', official_name: '', iso_alpha_two: 'RE', iso_alpha_three: 'ROU', iso_numeric: '642', tld: '' },
  { name: 'Romania', official_name: '', iso_alpha_two: 'RO', iso_alpha_three: 'RUS', iso_numeric: '643', tld: '' },
  { name: 'Russian Federation', official_name: '', iso_alpha_two: 'RU', iso_alpha_three: 'RWA', iso_numeric: '646', tld: '' },
  { name: 'Rwanda', official_name: '', iso_alpha_two: 'RW', iso_alpha_three: 'REU', iso_numeric: '638', tld: '' },
  { name: 'Saint Helena', official_name: '', iso_alpha_two: 'SH', iso_alpha_three: 'SHN', iso_numeric: '654', tld: '' },
  { name: 'Saint Kitts and Nevis', official_name: '', iso_alpha_two: 'KN', iso_alpha_three: 'KNA', iso_numeric: '659', tld: '' },
  { name: 'Saint Lucia', official_name: '', iso_alpha_two: 'LC', iso_alpha_three: 'LCA', iso_numeric: '662', tld: '' },
  { name: 'Saint Pierre and Miquelon', official_name: '', iso_alpha_two: 'PM', iso_alpha_three: 'SPM', iso_numeric: '666', tld: '' },
  { name: 'Saint Vincent and the Grenadines', official_name: '', iso_alpha_two: 'VC', iso_alpha_three: 'VCT', iso_numeric: '670', tld: '' },
  { name: 'Saint-Barthélemy', official_name: '', iso_alpha_two: 'BL', iso_alpha_three: 'BLM', iso_numeric: '652', tld: '' },
  { name: 'Saint-Martin (French part)', official_name: '', iso_alpha_two: 'MF', iso_alpha_three: 'MAF', iso_numeric: '663', tld: '' },
  { name: 'Samoa', official_name: '', iso_alpha_two: 'WS', iso_alpha_three: 'WSM', iso_numeric: '882', tld: '' },
  { name: 'San Marino', official_name: '', iso_alpha_two: 'SM', iso_alpha_three: 'SMR', iso_numeric: '674', tld: '' },
  { name: 'Sao Tome and Principe', official_name: '', iso_alpha_two: 'ST', iso_alpha_three: 'STP', iso_numeric: '678', tld: '' },
  { name: 'Saudi Arabia', official_name: '', iso_alpha_two: 'SA', iso_alpha_three: 'SAU', iso_numeric: '682', tld: '' },
  { name: 'Senegal', official_name: '', iso_alpha_two: 'SN', iso_alpha_three: 'SEN', iso_numeric: '686', tld: '' },
  { name: 'Serbia', official_name: '', iso_alpha_two: 'RS', iso_alpha_three: 'SRB', iso_numeric: '688', tld: '' },
  { name: 'Seychelles', official_name: '', iso_alpha_two: 'SC', iso_alpha_three: 'SYC', iso_numeric: '690', tld: '' },
  { name: 'Sierra Leone', official_name: '', iso_alpha_two: 'SL', iso_alpha_three: 'SLE', iso_numeric: '694', tld: '' },
  { name: 'Singapore', official_name: '', iso_alpha_two: 'SG', iso_alpha_three: 'SGP', iso_numeric: '702', tld: '' },
  { name: 'Slovakia', official_name: '', iso_alpha_two: 'SK', iso_alpha_three: 'SVK', iso_numeric: '703', tld: '' },
  { name: 'Slovenia', official_name: '', iso_alpha_two: 'SI', iso_alpha_three: 'SVN', iso_numeric: '705', tld: '' },
  { name: 'Solomon Islands', official_name: '', iso_alpha_two: 'SB', iso_alpha_three: 'SLB', iso_numeric: '090', tld: '' },
  { name: 'Somalia', official_name: '', iso_alpha_two: 'SO', iso_alpha_three: 'SOM', iso_numeric: '706', tld: '' },
  { name: 'South Africa', official_name: '', iso_alpha_two: 'ZA', iso_alpha_three: 'ZAF', iso_numeric: '710', tld: '' },
  { name: 'South Georgia and the South Sandwich Islands', official_name: '', iso_alpha_two: 'GS', iso_alpha_three: 'SGS', iso_numeric: '239', tld: '' },
  { name: 'South Sudan', official_name: '', iso_alpha_two: 'SS', iso_alpha_three: 'SSD', iso_numeric: '728', tld: '' },
  { name: 'Spain', official_name: '', iso_alpha_two: 'ES', iso_alpha_three: 'ESP', iso_numeric: '724', tld: '' },
  { name: 'Sri Lanka', official_name: '', iso_alpha_two: 'LK', iso_alpha_three: 'LKA', iso_numeric: '144', tld: '' },
  { name: 'Sudan', official_name: '', iso_alpha_two: 'SD', iso_alpha_three: 'SDN', iso_numeric: '736', tld: '' },
  { name: 'Surinam', official_name: '', iso_alpha_two: 'SR', iso_alpha_three: 'SUR', iso_numeric: '740', tld: '' },
  { name: 'Svalbard and Jan Mayen', official_name: '', iso_alpha_two: 'SJ', iso_alpha_three: 'SJM', iso_numeric: '744', tld: '' },
  { name: 'Swaziland', official_name: '', iso_alpha_two: 'SZ', iso_alpha_three: 'SWZ', iso_numeric: '748', tld: '' },
  { name: 'Sweden', official_name: '', iso_alpha_two: 'SE', iso_alpha_three: 'SWE', iso_numeric: '752', tld: '' },
  { name: 'Switzerland', official_name: '', iso_alpha_two: 'CH', iso_alpha_three: 'CHE', iso_numeric: '756', tld: '' },
  { name: 'Syrian Arab Republic (Syria)', official_name: '', iso_alpha_two: 'SY', iso_alpha_three: 'SYR', iso_numeric: '760', tld: '' },
  { name: 'Taiwan, Republic of China', official_name: '', iso_alpha_two: 'TW', iso_alpha_three: 'TWN', iso_numeric: '158', tld: '' },
  { name: 'Tajikistan', official_name: '', iso_alpha_two: 'TJ', iso_alpha_three: 'TJK', iso_numeric: '762', tld: '' },
  { name: 'Tanzania, United Republic of', official_name: '', iso_alpha_two: 'TZ', iso_alpha_three: 'TZA', iso_numeric: '834', tld: '' },
  { name: 'Thailand', official_name: '', iso_alpha_two: 'TH', iso_alpha_three: 'THA', iso_numeric: '764', tld: '' },
  { name: 'Timor-Leste', official_name: '', iso_alpha_two: 'TL', iso_alpha_three: 'TLS', iso_numeric: '626', tld: '' },
  { name: 'Togo', official_name: '', iso_alpha_two: 'TG', iso_alpha_three: 'TGO', iso_numeric: '768', tld: '' },
  { name: 'Tokelau', official_name: '', iso_alpha_two: 'TK', iso_alpha_three: 'TKL', iso_numeric: '772', tld: '' },
  { name: 'Tonga', official_name: '', iso_alpha_two: 'TO', iso_alpha_three: 'TON', iso_numeric: '776', tld: '' },
  { name: 'Trinidad and Tobago', official_name: '', iso_alpha_two: 'TT', iso_alpha_three: 'TTO', iso_numeric: '780', tld: '' },
  { name: 'Tunisia', official_name: '', iso_alpha_two: 'TN', iso_alpha_three: 'TUN', iso_numeric: '788', tld: '' },
  { name: 'Turkey', official_name: '', iso_alpha_two: 'TR', iso_alpha_three: 'TUR', iso_numeric: '792', tld: '' },
  { name: 'Turkmenistan', official_name: '', iso_alpha_two: 'TM', iso_alpha_three: 'TKM', iso_numeric: '795', tld: '' },
  { name: 'Turks and Caicos Islands', official_name: '', iso_alpha_two: 'TC', iso_alpha_three: 'TCA', iso_numeric: '796', tld: '' },
  { name: 'Tuvalu', official_name: '', iso_alpha_two: 'TV', iso_alpha_three: 'TUV', iso_numeric: '798', tld: '' },
  { name: 'Uganda', official_name: '', iso_alpha_two: 'UG', iso_alpha_three: 'UGA', iso_numeric: '800', tld: '' },
  { name: 'Ukraine', official_name: '', iso_alpha_two: 'UA', iso_alpha_three: 'UKR', iso_numeric: '804', tld: '' },
  { name: 'UAE', official_name: '', iso_alpha_two: 'AE', iso_alpha_three: 'ARE', iso_numeric: '784', tld: '' },
  { name: 'United Kingdom', official_name: '', iso_alpha_two: 'GB', iso_alpha_three: 'GBR', iso_numeric: '826', tld: '' },
  { name: 'United States', official_name: '', iso_alpha_two: 'US', iso_alpha_three: 'USA', iso_numeric: '840', tld: '' },
  { name: 'US Minor Outlying Islands', official_name: '', iso_alpha_two: 'UM', iso_alpha_three: 'URY', iso_numeric: '858', tld: '' },
  { name: 'Uruguay', official_name: '', iso_alpha_two: 'UY', iso_alpha_three: 'UMI', iso_numeric: '581', tld: '' },
  { name: 'Uzbekistan', official_name: '', iso_alpha_two: 'UZ', iso_alpha_three: 'UZB', iso_numeric: '860', tld: '' },
  { name: 'Vanuatu', official_name: '', iso_alpha_two: 'VU', iso_alpha_three: 'VUT', iso_numeric: '548', tld: '' },
  { name: 'Venezuela (Bolivarian Republic)', official_name: '', iso_alpha_two: 'VE', iso_alpha_three: 'VEN', iso_numeric: '862', tld: '' },
  { name: 'Viet Nam', official_name: '', iso_alpha_two: 'VN', iso_alpha_three: 'VNM', iso_numeric: '704', tld: '' },
  { name: 'Virgin Islands, US', official_name: '', iso_alpha_two: 'VI', iso_alpha_three: 'VIR', iso_numeric: '850', tld: '' },
  { name: 'Wallis and Futuna', official_name: '', iso_alpha_two: 'WF', iso_alpha_three: 'WLF', iso_numeric: '876', tld: '' },
  { name: 'Western Sahara', official_name: '', iso_alpha_two: 'EH', iso_alpha_three: 'ESH', iso_numeric: '723', tld: '' },
  { name: 'Yemen', official_name: '', iso_alpha_two: 'YE', iso_alpha_three: 'YEM', iso_numeric: '887', tld: '' },
  { name: 'Zambia', official_name: '', iso_alpha_two: 'ZM', iso_alpha_three: 'ZMB', iso_numeric: '894', tld: '' },
  { name: 'Zimbabwe', official_name: '', iso_alpha_two: 'ZW', iso_alpha_three: 'ZWE', iso_numeric: '716, tld: ''' }
].each do |c|
  Country.create(name: c[:name], iso_alpha_two: c[:iso_alpha_two], iso_alpha_three: c[:iso_alpha_three], iso_numeric: c[:iso_numeric])
end
