# frozen_string_literal: true
# Seeds for a Country model in a standard Relational Database.
# Schema is:
# Country { name: 'String', iso_alpha_two: 'String', iso_alpha_three: 'String', iso_numeric: 'Integer' }
#
[
  { name: 'Afghanistan', iso_alpha_two: 'AF', iso_alpha_three: 'AFG', iso_numeric: 004 },
  { name: 'ALA  Aland Islands', iso_alpha_two: 'AX', iso_alpha_three: 'ALA', iso_numeric: 248 },
  { name: 'Albania', iso_alpha_two: 'AL', iso_alpha_three: 'ALB', iso_numeric: 008 },
  { name: 'Algeria', iso_alpha_two: 'DZ', iso_alpha_three: 'DZA', iso_numeric: 012 },
  { name: 'American Samoa', iso_alpha_two: 'AS', iso_alpha_three: 'ASM', iso_numeric: 016 },
  { name: 'Andorra', iso_alpha_two: 'AD', iso_alpha_three: 'ND', iso_numeric: 020 },
  { name: 'Angola', iso_alpha_two: 'AO', iso_alpha_three: 'AGO', iso_numeric: 024 },
  { name: 'Anguilla', iso_alpha_two: 'AI', iso_alpha_three: 'AIA', iso_numeric: 660 },
  { name: 'Antarctica', iso_alpha_two: 'AQ', iso_alpha_three: 'ATA', iso_numeric: 010 },
  { name: 'Antigua And Barbuda', iso_alpha_two: 'AG', iso_alpha_three: 'ATG', iso_numeric: 028 },
  { name: 'Argentina', iso_alpha_two: 'AR', iso_alpha_three: 'ARG', iso_numeric: 032 },
  { name: 'Armenia', iso_alpha_two: 'AM', iso_alpha_three: 'ARM', iso_numeric: 051 },
  { name: 'Aruba', iso_alpha_two: 'AW', iso_alpha_three: 'ABW', iso_numeric: 533 },
  { name: 'Australia', iso_alpha_two: 'AU', iso_alpha_three: 'AUS', iso_numeric: 036 },
  { name: 'Austria', iso_alpha_two: 'AT', iso_alpha_three: 'AUT', iso_numeric: 040 },
  { name: 'Azerbaijan', iso_alpha_two: 'AZ', iso_alpha_three: 'AZE', iso_numeric: 031 },
  { name: 'Bahamas', iso_alpha_two: 'BS', iso_alpha_three: '', iso_numeric:  },
  { name: 'Bahrain', iso_alpha_two: 'BH', iso_alpha_three: '', iso_numeric:  },
  { name: 'Bangladesh', iso_alpha_two: 'BD', iso_alpha_three: '', iso_numeric:  },
  { name: 'Barbados', iso_alpha_two: 'BB', iso_alpha_three: '', iso_numeric:  },
  { name: 'Belarus', iso_alpha_two: 'BY', iso_alpha_three: '', iso_numeric:  },
  { name: 'Belgium', iso_alpha_two: 'BE', iso_alpha_three: '', iso_numeric:  },
  { name: 'Belize', iso_alpha_two: 'BZ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Benin', iso_alpha_two: 'BJ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Bermuda', iso_alpha_two: 'BM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Bhutan', iso_alpha_two: 'BT', iso_alpha_three: '', iso_numeric:  },
  { name: 'Bolivia', iso_alpha_two: 'BO', iso_alpha_three: '', iso_numeric:  },
  { name: 'Bosnia and Herzegovina', iso_alpha_two: 'BA', iso_alpha_three: '', iso_numeric:  },
  { name: 'Botswana', iso_alpha_two: 'BW', iso_alpha_three: '', iso_numeric:  },
  { name: 'Bouvet Island', iso_alpha_two: 'BV', iso_alpha_three: '', iso_numeric:  },
  { name: 'Brazil', iso_alpha_two: 'BR', iso_alpha_three: '', iso_numeric:  },
  { name: 'British Indian Ocean Territory', iso_alpha_two: 'IO', iso_alpha_three: '', iso_numeric:  },
  { name: 'Brunei Darussalam', iso_alpha_two: 'BN', iso_alpha_three: '', iso_numeric:  },
  { name: 'Bulgaria', iso_alpha_two: 'BG', iso_alpha_three: '', iso_numeric:  },
  { name: 'Burkina Faso', iso_alpha_two: 'BF', iso_alpha_three: '', iso_numeric:  },
  { name: 'Burundi', iso_alpha_two: 'BI', iso_alpha_three: '', iso_numeric:  },
  { name: 'Cambodia', iso_alpha_two: 'KH', iso_alpha_three: '', iso_numeric:  },
  { name: 'Cameroon', iso_alpha_two: 'CM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Canada', iso_alpha_two: 'CA', iso_alpha_three: '', iso_numeric:  },
  { name: 'Cape Verde', iso_alpha_two: 'CV', iso_alpha_three: '', iso_numeric:  },
  { name: 'Cayman Islands', iso_alpha_two: 'KY', iso_alpha_three: '', iso_numeric:  },
  { name: 'Central African Republic', iso_alpha_two: 'CF', iso_alpha_three: '', iso_numeric:  },
  { name: 'Chad', iso_alpha_two: 'TD', iso_alpha_three: '', iso_numeric:  },
  { name: 'Chile', iso_alpha_two: 'CL', iso_alpha_three: '', iso_numeric:  },
  { name: 'China', iso_alpha_two: 'CN', iso_alpha_three: '', iso_numeric:  },
  { name: 'Christmas Island', iso_alpha_two: 'CX', iso_alpha_three: '', iso_numeric:  },
  { name: 'Cocos (Keeling) Islands', iso_alpha_two: 'CC', iso_alpha_three: '', iso_numeric:  },
  { name: 'Colombia', iso_alpha_two: 'CO', iso_alpha_three: '', iso_numeric:  },
  { name: 'Comoros', iso_alpha_two: 'KM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Congo', iso_alpha_two: 'CG', iso_alpha_three: '', iso_numeric:  },
  { name: 'Congo (DRC)', iso_alpha_two: 'CD', iso_alpha_three: '', iso_numeric:  },
  { name: 'Cook Islands', iso_alpha_two: 'CK', iso_alpha_three: '', iso_numeric:  },
  { name: 'Costa Rica', iso_alpha_two: 'CR', iso_alpha_three: '', iso_numeric:  },
  { name: 'Cote d\'Ivoire', iso_alpha_two: 'CI', iso_alpha_three: '', iso_numeric:  },
  { name: 'Croatia', iso_alpha_two: 'HR', iso_alpha_three: '', iso_numeric:  },
  { name: 'Cuba', iso_alpha_two: 'CU', iso_alpha_three: '', iso_numeric:  },
  { name: 'Cyprus', iso_alpha_two: 'CY', iso_alpha_three: '', iso_numeric:  },
  { name: 'Czech Republic', iso_alpha_two: 'CZ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Denmark', iso_alpha_two: 'DK', iso_alpha_three: '', iso_numeric:  },
  { name: 'Djibouti', iso_alpha_two: 'DJ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Dominica', iso_alpha_two: 'DM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Dominican Republic', iso_alpha_two: 'DO', iso_alpha_three: '', iso_numeric:  },
  { name: 'Ecuador', iso_alpha_two: 'EC', iso_alpha_three: '', iso_numeric:  },
  { name: 'Egypt', iso_alpha_two: 'EG', iso_alpha_three: '', iso_numeric:  },
  { name: 'El Salvador', iso_alpha_two: 'SV', iso_alpha_three: '', iso_numeric:  },
  { name: 'Equatorial Guinea', iso_alpha_two: 'GQ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Eritrea', iso_alpha_two: 'ER', iso_alpha_three: '', iso_numeric:  },
  { name: 'Estonia', iso_alpha_two: 'EE', iso_alpha_three: '', iso_numeric:  },
  { name: 'Ethiopia', iso_alpha_two: 'ET', iso_alpha_three: '', iso_numeric:  },
  { name: 'Falkland Islands', iso_alpha_two: 'FK', iso_alpha_three: '', iso_numeric:  },
  { name: 'Faroe Islands', iso_alpha_two: 'FO', iso_alpha_three: '', iso_numeric:  },
  { name: 'Fiji', iso_alpha_two: 'FJ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Finland', iso_alpha_two: 'FI', iso_alpha_three: '', iso_numeric:  },
  { name: 'France', iso_alpha_two: 'FR', iso_alpha_three: '', iso_numeric:  },
  { name: 'French Guiana', iso_alpha_two: 'GF', iso_alpha_three: '', iso_numeric:  },
  { name: 'French Polynesia', iso_alpha_two: 'PF', iso_alpha_three: '', iso_numeric:  },
  { name: 'French Southern Territories', iso_alpha_two: 'TF', iso_alpha_three: '', iso_numeric:  },
  { name: 'Gabon', iso_alpha_two: 'GA', iso_alpha_three: '', iso_numeric:  },
  { name: 'Gambia', iso_alpha_two: 'GM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Georgia', iso_alpha_two: 'GE', iso_alpha_three: '', iso_numeric:  },
  { name: 'Germany', iso_alpha_two: 'DE', iso_alpha_three: '', iso_numeric:  },
  { name: 'Ghana', iso_alpha_two: 'GH', iso_alpha_three: '', iso_numeric:  },
  { name: 'Gibraltar', iso_alpha_two: 'GI', iso_alpha_three: '', iso_numeric:  },
  { name: 'Greece', iso_alpha_two: 'GR', iso_alpha_three: '', iso_numeric:  },
  { name: 'Greenland', iso_alpha_two: 'GL', iso_alpha_three: '', iso_numeric:  },
  { name: 'Grenada', iso_alpha_two: 'GD', iso_alpha_three: '', iso_numeric:  },
  { name: 'Guadeloupe', iso_alpha_two: 'GP', iso_alpha_three: '', iso_numeric:  },
  { name: 'Guam', iso_alpha_two: 'GU', iso_alpha_three: '', iso_numeric:  },
  { name: 'Guatemala', iso_alpha_two: 'GT', iso_alpha_three: '', iso_numeric:  },
  { name: 'Guernsey', iso_alpha_two: 'GG', iso_alpha_three: '', iso_numeric:  },
  { name: 'Guinea', iso_alpha_two: 'GN', iso_alpha_three: '', iso_numeric:  },
  { name: 'Guinea-Bissau', iso_alpha_two: 'GW', iso_alpha_three: '', iso_numeric:  },
  { name: 'Guyana', iso_alpha_two: 'GY', iso_alpha_three: '', iso_numeric:  },
  { name: 'Haiti', iso_alpha_two: 'HT', iso_alpha_three: '', iso_numeric:  },
  { name: 'Heard and McDonald Islands', iso_alpha_two: 'HM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Holy See (Vatican City State)', iso_alpha_two: 'VA', iso_alpha_three: '', iso_numeric:  },
  { name: 'Honduras', iso_alpha_two: 'HN', iso_alpha_three: '', iso_numeric:  },
  { name: 'Hong Kong', iso_alpha_two: 'HK', iso_alpha_three: '', iso_numeric:  },
  { name: 'Hungary', iso_alpha_two: 'HU', iso_alpha_three: '', iso_numeric:  },
  { name: 'Iceland', iso_alpha_two: 'IS', iso_alpha_three: '', iso_numeric:  },
  { name: 'India', iso_alpha_two: 'IN', iso_alpha_three: '', iso_numeric:  },
  { name: 'Indonesia', iso_alpha_two: 'ID', iso_alpha_three: '', iso_numeric:  },
  { name: 'Iran', iso_alpha_two: 'IR', iso_alpha_three: '', iso_numeric:  },
  { name: 'Iraq', iso_alpha_two: 'IQ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Ireland', iso_alpha_two: 'IE', iso_alpha_three: '', iso_numeric:  },
  { name: 'Isle of Man', iso_alpha_two: 'IM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Israel', iso_alpha_two: 'IL', iso_alpha_three: '', iso_numeric:  },
  { name: 'Italy', iso_alpha_two: 'IT', iso_alpha_three: '', iso_numeric:  },
  { name: 'Jamaica', iso_alpha_two: 'JM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Japan', iso_alpha_two: 'JP', iso_alpha_three: '', iso_numeric:  },
  { name: 'Jersey', iso_alpha_two: 'JE', iso_alpha_three: '', iso_numeric:  },
  { name: 'Jordan', iso_alpha_two: 'JO', iso_alpha_three: '', iso_numeric:  },
  { name: 'Kazakhstan', iso_alpha_two: 'KZ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Kenya', iso_alpha_two: 'KE', iso_alpha_three: '', iso_numeric:  },
  { name: 'Kiribati', iso_alpha_two: 'KI', iso_alpha_three: '', iso_numeric:  },
  { name: 'North Korea', iso_alpha_two: 'KP', iso_alpha_three: '', iso_numeric:  },
  { name: 'South Korea', iso_alpha_two: 'KR', iso_alpha_three: '', iso_numeric:  },
  { name: 'Kuwait', iso_alpha_two: 'KW', iso_alpha_three: '', iso_numeric:  },
  { name: 'Kyrgyzstan', iso_alpha_two: 'KG', iso_alpha_three: '', iso_numeric:  },
  { name: 'Laos', iso_alpha_two: 'LA', iso_alpha_three: '', iso_numeric:  },
  { name: 'Latvia', iso_alpha_two: 'LV', iso_alpha_three: '', iso_numeric:  },
  { name: 'Lebanon', iso_alpha_two: 'LB', iso_alpha_three: '', iso_numeric:  },
  { name: 'Lesotho', iso_alpha_two: 'LS', iso_alpha_three: '', iso_numeric:  },
  { name: 'Liberia', iso_alpha_two: 'LR', iso_alpha_three: '', iso_numeric:  },
  { name: 'Libya', iso_alpha_two: 'LY', iso_alpha_three: '', iso_numeric:  },
  { name: 'Liechtenstein', iso_alpha_two: 'LI', iso_alpha_three: '', iso_numeric:  },
  { name: 'Lithuania', iso_alpha_two: 'LT', iso_alpha_three: '', iso_numeric:  },
  { name: 'Luxembourg', iso_alpha_two: 'LU', iso_alpha_three: '', iso_numeric:  },
  { name: 'Macao', iso_alpha_two: 'MO', iso_alpha_three: '', iso_numeric:  },
  { name: 'Macedonia', iso_alpha_two: 'MK', iso_alpha_three: '', iso_numeric:  },
  { name: 'Madagascar', iso_alpha_two: 'MG', iso_alpha_three: '', iso_numeric:  },
  { name: 'Malawi', iso_alpha_two: 'MW', iso_alpha_three: '', iso_numeric:  },
  { name: 'Malaysia', iso_alpha_two: 'MY', iso_alpha_three: '', iso_numeric:  },
  { name: 'Maldives', iso_alpha_two: 'MV', iso_alpha_three: '', iso_numeric:  },
  { name: 'Mali', iso_alpha_two: 'ML', iso_alpha_three: '', iso_numeric:  },
  { name: 'Malta', iso_alpha_two: 'MT', iso_alpha_three: '', iso_numeric:  },
  { name: 'Marshall Islands', iso_alpha_two: 'MH', iso_alpha_three: '', iso_numeric:  },
  { name: 'Martinique', iso_alpha_two: 'MQ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Mauritania', iso_alpha_two: 'MR', iso_alpha_three: '', iso_numeric:  },
  { name: 'Mauritius', iso_alpha_two: 'MU', iso_alpha_three: '', iso_numeric:  },
  { name: 'Mayotte', iso_alpha_two: 'YT', iso_alpha_three: '', iso_numeric:  },
  { name: 'Mexico', iso_alpha_two: 'MX', iso_alpha_three: '', iso_numeric:  },
  { name: 'Micronesia', iso_alpha_two: 'FM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Moldova', iso_alpha_two: 'MD', iso_alpha_three: '', iso_numeric:  },
  { name: 'Monaco', iso_alpha_two: 'MC', iso_alpha_three: '', iso_numeric:  },
  { name: 'Mongolia', iso_alpha_two: 'MN', iso_alpha_three: '', iso_numeric:  },
  { name: 'Montenegro', iso_alpha_two: 'ME', iso_alpha_three: '', iso_numeric:  },
  { name: 'Montserrat', iso_alpha_two: 'MS', iso_alpha_three: '', iso_numeric:  },
  { name: 'Morocco', iso_alpha_two: 'MA', iso_alpha_three: '', iso_numeric:  },
  { name: 'Mozambique', iso_alpha_two: 'MZ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Myanmar', iso_alpha_two: 'MM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Namibia', iso_alpha_two: 'NA', iso_alpha_three: '', iso_numeric:  },
  { name: 'Nauru', iso_alpha_two: 'NR', iso_alpha_three: '', iso_numeric:  },
  { name: 'Nepal', iso_alpha_two: 'NP', iso_alpha_three: '', iso_numeric:  },
  { name: 'Netherlands', iso_alpha_two: 'NL', iso_alpha_three: '', iso_numeric:  },
  { name: 'Netherlands Antilles', iso_alpha_two: 'AN', iso_alpha_three: '', iso_numeric:  },
  { name: 'New Caledonia', iso_alpha_two: 'NC', iso_alpha_three: '', iso_numeric:  },
  { name: 'New Zealand', iso_alpha_two: 'NZ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Nicaragua', iso_alpha_two: 'NI', iso_alpha_three: '', iso_numeric:  },
  { name: 'Niger', iso_alpha_two: 'NE', iso_alpha_three: '', iso_numeric:  },
  { name: 'Nigeria', iso_alpha_two: 'NG', iso_alpha_three: '', iso_numeric:  },
  { name: 'Niue', iso_alpha_two: 'NU', iso_alpha_three: '', iso_numeric:  },
  { name: 'Norfolk Island', iso_alpha_two: 'NF', iso_alpha_three: '', iso_numeric:  },
  { name: 'Northern Mariana Islands', iso_alpha_two: 'MP', iso_alpha_three: '', iso_numeric:  },
  { name: 'Norway', iso_alpha_two: 'NO', iso_alpha_three: '', iso_numeric:  },
  { name: 'Oman', iso_alpha_two: 'OM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Pakistan', iso_alpha_two: 'PK', iso_alpha_three: '', iso_numeric:  },
  { name: 'Palau', iso_alpha_two: 'PW', iso_alpha_three: '', iso_numeric:  },
  { name: 'Palestinian Territory', iso_alpha_two: 'PS', iso_alpha_three: '', iso_numeric:  },
  { name: 'Panama', iso_alpha_two: 'PA', iso_alpha_three: '', iso_numeric:  },
  { name: 'Papua New Guinea', iso_alpha_two: 'PG', iso_alpha_three: '', iso_numeric:  },
  { name: 'Paraguay', iso_alpha_two: 'PY', iso_alpha_three: '', iso_numeric:  },
  { name: 'Peru', iso_alpha_two: 'PE', iso_alpha_three: '', iso_numeric:  },
  { name: 'Philippines', iso_alpha_two: 'PH', iso_alpha_three: '', iso_numeric:  },
  { name: 'Pitcairn', iso_alpha_two: 'PN', iso_alpha_three: '', iso_numeric:  },
  { name: 'Poland', iso_alpha_two: 'PL', iso_alpha_three: '', iso_numeric:  },
  { name: 'Portugal', iso_alpha_two: 'PT', iso_alpha_three: '', iso_numeric:  },
  { name: 'Puerto Rico', iso_alpha_two: 'PR', iso_alpha_three: '', iso_numeric:  },
  { name: 'Qatar', iso_alpha_two: 'QA', iso_alpha_three: '', iso_numeric:  },
  { name: 'Reunion', iso_alpha_two: 'RE', iso_alpha_three: '', iso_numeric:  },
  { name: 'Romania', iso_alpha_two: 'RO', iso_alpha_three: '', iso_numeric:  },
  { name: 'Russia', iso_alpha_two: 'RU', iso_alpha_three: '', iso_numeric:  },
  { name: 'Rwanda', iso_alpha_two: 'RW', iso_alpha_three: '', iso_numeric:  },
  { name: 'Saint Barthelemy', iso_alpha_two: 'BL', iso_alpha_three: '', iso_numeric:  },
  { name: 'Saint Helena', iso_alpha_two: 'SH', iso_alpha_three: '', iso_numeric:  },
  { name: 'Saint Kitts and Nevis', iso_alpha_two: 'KN', iso_alpha_three: '', iso_numeric:  },
  { name: 'Saint Lucia', iso_alpha_two: 'LC', iso_alpha_three: '', iso_numeric:  },
  { name: 'Saint Pierre and Miquelon', iso_alpha_two: 'PM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Saint Vincent and the Grenadines', iso_alpha_two: 'VC', iso_alpha_three: '', iso_numeric:  },
  { name: 'Samoa', iso_alpha_two: 'WS', iso_alpha_three: '', iso_numeric:  },
  { name: 'San Marino', iso_alpha_two: 'SM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Sao Tome and Principe', iso_alpha_two: 'ST', iso_alpha_three: '', iso_numeric:  },
  { name: 'Saudi Arabia', iso_alpha_two: 'SA', iso_alpha_three: '', iso_numeric:  },
  { name: 'Senegal', iso_alpha_two: 'SN', iso_alpha_three: '', iso_numeric:  },
  { name: 'Serbia', iso_alpha_two: 'RS', iso_alpha_three: '', iso_numeric:  },
  { name: 'Seychelles', iso_alpha_two: 'SC', iso_alpha_three: '', iso_numeric:  },
  { name: 'Sierra Leone', iso_alpha_two: 'SL', iso_alpha_three: '', iso_numeric:  },
  { name: 'Singapore', iso_alpha_two: 'SG', iso_alpha_three: '', iso_numeric:  },
  { name: 'Slovakia', iso_alpha_two: 'SK', iso_alpha_three: '', iso_numeric:  },
  { name: 'Slovenia', iso_alpha_two: 'SI', iso_alpha_three: '', iso_numeric:  },
  { name: 'Solomon Islands', iso_alpha_two: 'SB', iso_alpha_three: '', iso_numeric:  },
  { name: 'Somalia', iso_alpha_two: 'SO', iso_alpha_three: '', iso_numeric:  },
  { name: 'South Africa', iso_alpha_two: 'ZA', iso_alpha_three: '', iso_numeric:  },
  { name: 'South Georgia and the South Sandwich Islands', iso_alpha_two: 'GS', iso_alpha_three: '', iso_numeric:  },
  { name: 'Spain', iso_alpha_two: 'ES', iso_alpha_three: '', iso_numeric:  },
  { name: 'Sri Lanka', iso_alpha_two: 'LK', iso_alpha_three: '', iso_numeric:  },
  { name: 'Sudan', iso_alpha_two: 'SD', iso_alpha_three: '', iso_numeric:  },
  { name: 'Surinam', iso_alpha_two: 'SR', iso_alpha_three: '', iso_numeric:  },
  { name: 'Svalbard and Jan Mayen', iso_alpha_two: 'SJ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Swaziland', iso_alpha_two: 'SZ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Sweden', iso_alpha_two: 'SE', iso_alpha_three: '', iso_numeric:  },
  { name: 'Switzerland', iso_alpha_two: 'CH', iso_alpha_three: '', iso_numeric:  },
  { name: 'Syria', iso_alpha_two: 'SY', iso_alpha_three: '', iso_numeric:  },
  { name: 'Taiwan', iso_alpha_two: 'TW', iso_alpha_three: '', iso_numeric:  },
  { name: 'Tajikistan', iso_alpha_two: 'TJ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Tanzania', iso_alpha_two: 'TZ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Thailand', iso_alpha_two: 'TH', iso_alpha_three: '', iso_numeric:  },
  { name: 'Timor-Leste', iso_alpha_two: 'TL', iso_alpha_three: '', iso_numeric:  },
  { name: 'Togo', iso_alpha_two: 'TG', iso_alpha_three: '', iso_numeric:  },
  { name: 'Tokelau', iso_alpha_two: 'TK', iso_alpha_three: '', iso_numeric:  },
  { name: 'Tonga', iso_alpha_two: 'TO', iso_alpha_three: '', iso_numeric:  },
  { name: 'Trinidad and Tobago', iso_alpha_two: 'TT', iso_alpha_three: '', iso_numeric:  },
  { name: 'Tunisia', iso_alpha_two: 'TN', iso_alpha_three: '', iso_numeric:  },
  { name: 'Turkey', iso_alpha_two: 'TR', iso_alpha_three: '', iso_numeric:  },
  { name: 'Turkmenistan', iso_alpha_two: 'TM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Turks and Caicos Islands', iso_alpha_two: 'TC', iso_alpha_three: '', iso_numeric:  },
  { name: 'Tuvalu', iso_alpha_two: 'TV', iso_alpha_three: '', iso_numeric:  },
  { name: 'Uganda', iso_alpha_two: 'UG', iso_alpha_three: '', iso_numeric:  },
  { name: 'Ukraine', iso_alpha_two: 'UA', iso_alpha_three: '', iso_numeric:  },
  { name: 'UAE', iso_alpha_two: 'AE', iso_alpha_three: '', iso_numeric:  },
  { name: 'United Kingdom', iso_alpha_two: 'GB', iso_alpha_three: '', iso_numeric:  },
  { name: 'United States', iso_alpha_two: 'US', iso_alpha_three: '', iso_numeric:  },
  { name: 'United States Minor Outlying Islands', iso_alpha_two: 'UM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Uruguay', iso_alpha_two: 'UY', iso_alpha_three: '', iso_numeric:  },
  { name: 'Uzbekistan', iso_alpha_two: 'UZ', iso_alpha_three: '', iso_numeric:  },
  { name: 'Vanuatu', iso_alpha_two: 'VU', iso_alpha_three: '', iso_numeric:  },
  { name: 'Venezuela', iso_alpha_two: 'VE', iso_alpha_three: '', iso_numeric:  },
  { name: 'Vietnam', iso_alpha_two: 'VN', iso_alpha_three: '', iso_numeric:  },
  { name: 'British Virgin Islands', iso_alpha_two: 'VG', iso_alpha_three: '', iso_numeric:  },
  { name: 'US Virgin Islands', iso_alpha_two: 'VI', iso_alpha_three: '', iso_numeric:  },
  { name: 'Wallis and Futuna', iso_alpha_two: 'WF', iso_alpha_three: '', iso_numeric:  },
  { name: 'Western Sahara', iso_alpha_two: 'EH', iso_alpha_three: '', iso_numeric:  },
  { name: 'Yemen', iso_alpha_two: 'YE', iso_alpha_three: '', iso_numeric:  },
  { name: 'Zambia', iso_alpha_two: 'ZM', iso_alpha_three: '', iso_numeric:  },
  { name: 'Zimbabwe', iso_alpha_two: 'ZW', iso_alpha_three: '', iso_numeric:  }
].each do |c|
  Country.create(name: c[:name], iso_two_letter_code: c[:iso_two_letter_code])
end
